event_brite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'event_brite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('get_data.urls', namespace='get_data')),
]

get_data/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'event_brite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^event/', views.EventDetailView.as_view(), name="event_detail"),
    url(r'^$', views.CategoriesSelectionView.as_view(), name="select_categories"),
]

get_data/models.py
from django.db import models

# Create your models here.

get_data/views.py
from django.views import generic
from django.conf import settings
from django.core.urlresolvers import reverse_lazy
import requests

# Create your views here.

EVENT_URL = "https://www.eventbriteapi.com/v3/events/search/"
CATEGORIES_URL = "https://www.eventbriteapi.com/v3/categories/"


class CategoriesSelectionView(generic.TemplateView):
    template_name = 'get_data/category_select.html'

    def get_context_data(self, **kwargs):
        # overwrite the get_context_data
        context = super(CategoriesSelectionView, self).get_context_data(**kwargs)
        context['token'] = settings.EVENTBRITE_TOKEN  # set EventBrite Token
        context['categories'] = self.get_categories()['categories']  # set all categories
        return context

    @staticmethod
    def get_categories(page=None):
        """
        Get all the categories and return it into the json.
        """
        token = settings.EVENTBRITE_TOKEN
        categories_url = "%s?token=%s&page=%s" % (CATEGORIES_URL, token, page)
        data = requests.get(categories_url)
        return data.json()


class EventDetailView(generic.TemplateView):
    template_name = 'get_data/event_detail.html'

    def get_context_data(self, **kwargs):
        # overwrite the get_context_data
        context = super(EventDetailView, self).get_context_data(**kwargs)
        categories = self.request.GET.get('categories', None)
        context['event_data'] = None
        context['categories'] = categories
        context['page_url'] = "%s?categories=%s" % (reverse_lazy('get_data:event_detail'), categories)
        if categories:
            page = self.request.GET.get('page', None)
            context['event_data'] = self.get_event_data(page, categories)  # set event data
        return context

    @staticmethod
    def get_event_data(page, categories):
        """
        Get all the events of categories.
        """
        token = settings.EVENTBRITE_TOKEN
        event_url = "%s?token=%s&categories=%s&page=%s" % (EVENT_URL, token, categories, page)
        data = requests.get(event_url)
        return data.json()

get_data/templates/get_data/category_select.html
{% extends 'get_data/layout/base.html' %}
{% load staticfiles %}

{% block body_block %}

    <div class="container theme-showcase" role="main">
        <h2>Categories</h2>
        <hr>
        <div id="categories" class="col-lg-offset-1 col-lg-10">
            {% if categories %}

                <h3>Please Select maximum 3 categories </h3>

                <div class="row">
                    {% for cat in categories %}
                        <div class="col-lg-3">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" value="{{ cat.id }}" class="ck_category">{{ cat.name }}
                                </label>
                            </div>
                        </div>
                    {% endfor %}

                    <p class="text-center">
                        <button class="btn btn-primary" type="button" id="getEvent">Select Category</button>
                    </p>

                </div>
            {% endif %}
        </div>


    </div> <!-- /container -->

{% endblock %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
{% endblock %}

get_data/templates/get_data/event_detail.html
{% extends 'get_data/layout/base.html' %}
{% load staticfiles %}
{% load date_format %}

{% block css_header %}
    {{ block.super }}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body_block %}

    <div class="container theme-showcase" role="main">
        <ol class="breadcrumb">
            <li><a href="{% url 'get_data:select_categories' %}">Select Categories</a></li>
            <li class="active">Event Details</li>
        </ol>

        <div class="loader hide">

        </div>

        <div class="page-header">
            <h1>Your Selected Categories Event</h1>
        </div>
        <div class="paginate"  data-total-page="{{ event_data.pagination.page_count }}" data-current-page="{{ event_data.pagination.page_number }}" data-url="{{ page_url }}"></div>

        {% if event_data %}
            <div class="row">
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th width="15%">Name</th>
                        <th width="8%">Logo</th>
                        <th width="33%">Discription</th>
                        <th  width="17%">Start Date</th>
                        <th  width="17%">End Date</th>
                        <th  width="10%">Capacity</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for data in event_data.events %}
                        <tr>
                            <td width="15%">{% autoescape on %}{{ data.name.text }}{% endautoescape %}</td>
                            <td width="8%"><img src="{{ data.logo.url }}" alt="logo" width="80px" height="40px"/></td>
                            <td width="33%" data-toggle="tooltip" title="{{ data.description.text }}">{% autoescape on %}{{ data.description.text }}{% endautoescape %}</td>
                            <td width="17%">{% date_time data.start.local %} {{ data.start.timezone }}</td>
                            <td width="17%">{% date_time data.end.local %} {{ data.end.timezone }}</td>
                            <td width="10%">{{ data.capacity }}</td>

                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <div class="paginate"  data-total-page="{{ event_data.pagination.page_count }}" data-current-page="{{ event_data.pagination.page_number }}" data-url="{{ page_url }}"></div>

        {% endif %}


    </div> <!-- /container -->





{% endblock %}

{% block js_footer %}
    {{ block.super }}
    <script src="{% static 'js/jquery.bootpag.min.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>
    <script src="{% static 'js/event-detail.js' %}"></script>
{% endblock %}

get_data/templates/get_data/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/html">
<head>

    <!-- ==============================================
    Title and Meta Tags
    =============================================== -->
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <title>{% block page_title %}Basic Project{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="HTML, CSS, XML, XHTML, JavaScript">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- ==============================================
    CSS
    =============================================== -->
    {% block css_header %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock %}

</head>
<body class="main-bg">

<!-- ==============================================
Main Body
=============================================== -->
{% block body_block %}
{% endblock %}

<!-- ==============================================
Java-scripts
=============================================== -->
{% block js_footer %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock %}

</body>
</html>